In [1]:
import numpy as np

array(['Pakora', 'Samoosa', 'Rayita'], dtype='<U7')

## creating an array using numpy (1-D array)

In [12]:
food = np.array(["Pakora", "Samoosa", "Rayita"])
food

array(['Pakora', 'Samoosa', 'Rayita'], dtype='<U7')

In [5]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [3]:
type(food)

numpy.ndarray

In [6]:
len(price)

3

In [7]:
price[0]

5

In [8]:
price[0:]

array([5, 5, 5])

In [9]:
food[1]

'Samoosa'

In [10]:
price.mean()

5.0

## Range Method of Creating arrays.

In [13]:
# zero methoddd
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
#empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [17]:
#range 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [21]:
# specify interval
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [22]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
#line space
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
# specify ur data type
np.ones(50, dtype= np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [26]:
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## array functions

In [28]:
a = np.array([10,12,15,2,4,6,100,0.5,10.4])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. ,   0.5,  10.4])

In [30]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.4,  12. ,  15. , 100. ])

In [32]:
b = np.array([10.3,33,0.3,4,5,6])
b

array([10.3, 33. ,  0.3,  4. ,  5. ,  6. ])

In [33]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.4,  12. ,  15. , 100. ,
        10.3,  33. ,   0.3,   4. ,   5. ,   6. ])

In [38]:
c.sort()
c

array([  0.3,   0.5,   2. ,   4. ,   4. ,   5. ,   6. ,   6. ,  10. ,
        10.3,  10.4,  12. ,  15. ,  33. , 100. ])

# 2D - Array 

In [46]:
a = np.array([[1,2],[5,4]])
a

array([[1, 2],
       [5, 4]])

In [43]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [47]:
c = np.concatenate((a,b), axis=0)
c

array([[1, 2],
       [5, 4],
       [6, 7],
       [8, 9]])

In [49]:
c= np.concatenate((a,b), axis=1)
c

array([[1, 2, 6, 7],
       [5, 4, 8, 9]])

In [53]:
a = np.array([[[0,1,2,3],[4,5,6,7]],
              [[0,1,2,3],[4,5,6,7]],
             [[0,1,2,3],[4,5,6,7]]
             ])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [54]:
# to find the number of dimnesions
a.ndim

3

In [56]:
b= np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b.ndim

2

In [58]:
#size(numer od elements)
a.size

24

In [61]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [59]:
# shape of array
a.shape

(3, 2, 4)

In [64]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
# reshape
b = a.reshape(3,3) # 3*3=9
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
# reshape
np.reshape(a, newshape=(1,9), order ='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
# reshape
np.reshape(a, newshape=(1,9), order ='C')

In [67]:
# convert 1-D into 2-D array
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
a.shape

(9,)

In [69]:
# rowwise 2D conversion
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
b.shape

(1, 9)

In [71]:
# colooumn wise 2D conversion
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [72]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
# indexing
a[2:6]

array([3, 4, 5, 6])

In [74]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [75]:
a+5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])